# Generated by Django 3.1.4 on 2021-01-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=999, null=True)),
                ('slug', models.SlugField(blank=True, max_length=999, null=True)),
            ],
        ),
    ]
