# Generated by Django 3.1.4 on 2021-01-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='ReleaseStatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
