# Generated by Django 3.1.4 on 2021-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorys', '0002_categorys_releasestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys_ManyToManyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Article', models.CharField(blank=True, max_length=999, null=True)),
                ('id_Category', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
    ]
