# Generated by Django 3.1.4 on 2021-01-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorys', '0003_categorys_manytomanyfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorys_manytomanyfield',
            old_name='id_Article',
            new_name='Article_id',
        ),
        migrations.RenameField(
            model_name='categorys_manytomanyfield',
            old_name='id_Category',
            new_name='Category_id',
        ),
    ]
