# Generated by Django 3.1.4 on 2021-01-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorys', '0005_auto_20210107_1426'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys_ManyToManyField',
            new_name='Categorys_Article',
        ),
    ]
