# Generated by Django 3.1.4 on 2021-01-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorys', '0006_auto_20210107_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys_article',
            name='Article_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categorys_article',
            name='Category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
