# Generated by Django 3.1.4 on 2021-01-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description_instagram',
            field=models.TextField(blank=True, null=True),
        ),
    ]
