# Generated by Django 3.1.4 on 2021-01-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_categorys', '0001_initial'),
        ('blog_Articles', '0003_remove_articles_description_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='categorys',
            field=models.ManyToManyField(blank=True, null=True, to='blog_categorys.Categorys'),
        ),
    ]
