# Generated by Django 3.1.4 on 2021-01-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_Articles', '0004_articles_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='categorys',
        ),
    ]
